### ISSUE TITLE
Demo: 404 errors because of wrong relative paths

### ISSUE THREAD

**Issue by jledentu** [manekinekko/drag-resize#1]
Hi,

The demo doesn't work on my computer. I've some 404 errors on the component's dependencies, because I don't have any `bower_components` dir in the component directory.

```
demo.html:16 GET http://localhost:8080/drag-resize/bower_components/webcomponentsjs/webcomponents.min.js 
demo.html:70 GET http://localhost:8080/drag-resize/bower_components/polymer/polymer.html 404 (Not Found)
demo.html:70 GET http://localhost:8080/drag-resize/bower_components/core-drag-drop/core-drag-drop.html 404 (Not Found)
demo.html:70 GET http://localhost:8080/drag-resize/bower_components/core-tooltip/core-tooltip.html 404 (Not Found)
drag-resize.html:58 Uncaught ReferenceError: Polymer is not defined
demo.html:69 Uncaught ReferenceError: wrap is not defined
```

You should assume that the bower dependencies directory is the parent directory.

**Comment by manekinekko** [comment]
Hi Jerome, 
In order to try out the demo file, you just need to clone the repo and run `bower install`. Then serve the [demo.html](https://raw.githubusercontent.com/manekinekko/drag-resize/master/demo.html) and you're ready to go. If you check the `.bowerrc` you'll see that bower installs its deps inside the `bower_components` at the same folder as the [demo.html](https://raw.githubusercontent.com/manekinekko/drag-resize/master/demo.html).

I just tried it right now inside a clean folder and the demo runs fine. Could you try again and tell me please?

Thx.

**Comment by frasator** [comment]
Hello, 

I am getting the same error, when I install the component as a dep with 
bower install drag-resize

This is a guide I have just found:
https://www.polymer-project.org/articles/distributing-components-with-bower.html#reference-dependencies 

It is recommended to use relative paths to make the component usable for everyone.

Thank you!

**Comment by manekinekko** [comment]
Hi Pako. Could you please try again, I've submitted a new fix (32eef74894720914e37e552bfcade6779243e881).

Thx.

PS: I'll wait for your answer before submitting an update to Bower.

**Comment by jledentu** [comment]
Hi Wassim,

With this new fix, it works perfectly. Thanks!

**Comment by manekinekko** [comment]
thx @jledentu .
